---
version: '2'
services:
  snapserver:
    image: radusuciu/pi4snap
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
    devices:
      - /dev/snd:/dev/snd
    restart: always
