version: '3'

services:
  snapserver:
    build:
      context: .
      target: snapserver
    image: radusuciu/pi4snap:librespot
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - ./snapserver.conf.template:/etc/snapserver.conf/template
    environment:
      SPOTIFY_USERNAME: ${SPOTIFY_USERNAME:-}
      SPOTIFY_PASSWORD: ${SPOTIFY_PASSWORD:-}
    devices:
      - /dev/snd:/dev/snd
    restart: always
