version: '3'

services:
  snapserver:
    build:
      context: .
      target: snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
      - ./snapweb/snapweb-0.1.0/dist:/usr/share/snapserver/snapweb
    environment:
      SPOTIFY_USERNAME: ${SPOTIFY_USERNAME:-}
      SPOTIFY_PASSWORD: ${SPOTIFY_PASSWORD:-}
    devices:
      - /dev/snd:/dev/snd
    restart: always
